[2022-07-26 02:30:26,890] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: GOOG_historic_data.load_historic_data_into_postgres manual__2022-07-26T02:30:19.186031+00:00 [queued]>
[2022-07-26 02:30:26,899] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: GOOG_historic_data.load_historic_data_into_postgres manual__2022-07-26T02:30:19.186031+00:00 [queued]>
[2022-07-26 02:30:26,900] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-07-26 02:30:26,900] {taskinstance.py:1377} INFO - Starting attempt 1 of 2
[2022-07-26 02:30:26,900] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-07-26 02:30:26,914] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): load_historic_data_into_postgres> on 2022-07-26 02:30:19.186031+00:00
[2022-07-26 02:30:26,918] {standard_task_runner.py:52} INFO - Started process 15424 to run task
[2022-07-26 02:30:26,920] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'GOOG_historic_data', 'load_historic_data_into_postgres', 'manual__2022-07-26T02:30:19.186031+00:00', '--job-id', '82', '--raw', '--subdir', 'DAGS_FOLDER/open_options.py', '--cfg-path', '/tmp/tmpsopu0zwi', '--error-file', '/tmp/tmpsco2v_6y']
[2022-07-26 02:30:26,921] {standard_task_runner.py:80} INFO - Job 82: Subtask load_historic_data_into_postgres
[2022-07-26 02:30:27,010] {task_command.py:371} INFO - Running <TaskInstance: GOOG_historic_data.load_historic_data_into_postgres manual__2022-07-26T02:30:19.186031+00:00 [running]> on host 527e7914f635
[2022-07-26 02:30:27,166] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=vardhan
AIRFLOW_CTX_DAG_ID=GOOG_historic_data
AIRFLOW_CTX_TASK_ID=load_historic_data_into_postgres
AIRFLOW_CTX_EXECUTION_DATE=2022-07-26T02:30:19.186031+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-07-26T02:30:19.186031+00:00
[2022-07-26 02:30:27,555] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/open_options.py", line 337, in load_historic_data_into_postgres
    postgres_hook.run(query_insert % str(row))
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 204, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/hooks/postgres.py", line 86, in get_conn
    conn = deepcopy(self.connection or self.get_connection(conn_id))
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/base.py", line 67, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/connection.py", line 430, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgres_default` isn't defined
[2022-07-26 02:30:27,562] {taskinstance.py:1420} INFO - Marking task as UP_FOR_RETRY. dag_id=GOOG_historic_data, task_id=load_historic_data_into_postgres, execution_date=20220726T023019, start_date=20220726T023026, end_date=20220726T023027
[2022-07-26 02:30:27,577] {standard_task_runner.py:97} ERROR - Failed to execute job 82 for task load_historic_data_into_postgres (The conn_id `postgres_default` isn't defined; 15424)
[2022-07-26 02:30:27,616] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-07-26 02:30:27,679] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
