[2022-07-26 03:08:51,797] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: GOOG_historic_data.load_historic_data_into_postgres manual__2022-07-26T03:07:42.935066+00:00 [queued]>
[2022-07-26 03:08:51,807] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: GOOG_historic_data.load_historic_data_into_postgres manual__2022-07-26T03:07:42.935066+00:00 [queued]>
[2022-07-26 03:08:51,807] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-07-26 03:08:51,807] {taskinstance.py:1377} INFO - Starting attempt 1 of 2
[2022-07-26 03:08:51,808] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-07-26 03:08:51,826] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): load_historic_data_into_postgres> on 2022-07-26 03:07:42.935066+00:00
[2022-07-26 03:08:51,831] {standard_task_runner.py:52} INFO - Started process 30643 to run task
[2022-07-26 03:08:51,833] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'GOOG_historic_data', 'load_historic_data_into_postgres', 'manual__2022-07-26T03:07:42.935066+00:00', '--job-id', '151', '--raw', '--subdir', 'DAGS_FOLDER/open_options.py', '--cfg-path', '/tmp/tmp2cim7aee', '--error-file', '/tmp/tmpap62zbsz']
[2022-07-26 03:08:51,835] {standard_task_runner.py:80} INFO - Job 151: Subtask load_historic_data_into_postgres
[2022-07-26 03:08:51,901] {task_command.py:371} INFO - Running <TaskInstance: GOOG_historic_data.load_historic_data_into_postgres manual__2022-07-26T03:07:42.935066+00:00 [running]> on host 527e7914f635
[2022-07-26 03:08:52,020] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=vardhan
AIRFLOW_CTX_DAG_ID=GOOG_historic_data
AIRFLOW_CTX_TASK_ID=load_historic_data_into_postgres
AIRFLOW_CTX_EXECUTION_DATE=2022-07-26T03:07:42.935066+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-07-26T03:07:42.935066+00:00
[2022-07-26 03:08:52,389] {base.py:68} INFO - Using connection ID 'postgres_optionsdata' for task execution.
[2022-07-26 03:08:52,395] {dbapi.py:231} INFO - Running statement: INSERT INTO historic_GOOG (datetime, high, low, open, close, volume) VALUES (1654691040000, 116.95, 116.95, 116.95, 116.95, 4000) ON CONFLICT DO NOTHING, parameters: None
[2022-07-26 03:08:52,398] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/open_options.py", line 331, in load_historic_data_into_postgres
    postgres_hook.run(query_insert % str(row))
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 211, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 235, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UndefinedColumn: column "datetime" of relation "historic_goog" does not exist
LINE 1: INSERT INTO historic_GOOG (datetime, high, low, open, close,...
                                   ^

[2022-07-26 03:08:52,418] {taskinstance.py:1420} INFO - Marking task as UP_FOR_RETRY. dag_id=GOOG_historic_data, task_id=load_historic_data_into_postgres, execution_date=20220726T030742, start_date=20220726T030851, end_date=20220726T030852
[2022-07-26 03:08:52,441] {standard_task_runner.py:97} ERROR - Failed to execute job 151 for task load_historic_data_into_postgres (column "datetime" of relation "historic_goog" does not exist
LINE 1: INSERT INTO historic_GOOG (datetime, high, low, open, close,...
                                   ^
; 30643)
[2022-07-26 03:08:52,487] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-07-26 03:08:52,583] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
