[2022-07-22 14:15:02,730] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: get_options_data_FB.create_table manual__2022-07-22T14:15:01.825087+00:00 [queued]>
[2022-07-22 14:15:02,747] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: get_options_data_FB.create_table manual__2022-07-22T14:15:01.825087+00:00 [queued]>
[2022-07-22 14:15:02,748] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-07-22 14:15:02,748] {taskinstance.py:1377} INFO - Starting attempt 1 of 2
[2022-07-22 14:15:02,748] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-07-22 14:15:02,771] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): create_table> on 2022-07-22 14:15:01.825087+00:00
[2022-07-22 14:15:02,780] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'get_options_data_FB', 'create_table', 'manual__2022-07-22T14:15:01.825087+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/open_options.py', '--cfg-path', '/tmp/tmp10sydf71', '--error-file', '/tmp/tmpq13ht0_s']
[2022-07-22 14:15:02,776] {standard_task_runner.py:52} INFO - Started process 367 to run task
[2022-07-22 14:15:02,782] {standard_task_runner.py:80} INFO - Job 3: Subtask create_table
[2022-07-22 14:15:02,861] {task_command.py:371} INFO - Running <TaskInstance: get_options_data_FB.create_table manual__2022-07-22T14:15:01.825087+00:00 [running]> on host 6ca3a31f58ff
[2022-07-22 14:15:02,946] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=chrischow
AIRFLOW_CTX_DAG_ID=get_options_data_FB
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2022-07-22T14:15:01.825087+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-07-22T14:15:01.825087+00:00
[2022-07-22 14:15:02,958] {base.py:68} INFO - Using connection ID 'postgres_optionsdata' for task execution.
[2022-07-22 14:15:02,965] {dbapi.py:231} INFO - Running statement: 
CREATE TABLE IF NOT EXISTS FB (
    put_call VARCHAR(5) NOT NULL,
    symbol VARCHAR(32) NOT NULL,
    description VARCHAR(64) NOT NULL,
    bid DOUBLE PRECISION,
    ask DOUBLE PRECISION,
    last DOUBLE PRECISION,
    bid_size INTEGER,
    ask_size INTEGER,
    last_size INTEGER,
    high_price DOUBLE PRECISION,
    low_price DOUBLE PRECISION,
    open_price DOUBLE PRECISION,
    close_price DOUBLE PRECISION,
    total_volume INTEGER,
    quote_time BIGINT,
    volatility DOUBLE PRECISION,
    delta DOUBLE PRECISION,
    gamma DOUBLE PRECISION,
    theta DOUBLE PRECISION,
    vega DOUBLE PRECISION,
    rho DOUBLE PRECISION,
    open_interest INTEGER,
    time_value DOUBLE PRECISION,
    theoretical_value DOUBLE PRECISION,
    strike_price DOUBLE PRECISION,
    expiration_date BIGINT,
    dte INTEGER,
    PRIMARY KEY (symbol, quote_time)
)
, parameters: None
[2022-07-22 14:15:02,973] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/open_options.py", line 68, in create_table
    """)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 211, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 235, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "pg_type_typname_nsp_index"
DETAIL:  Key (typname, typnamespace)=(fb, 2200) already exists.

[2022-07-22 14:15:02,985] {taskinstance.py:1420} INFO - Marking task as UP_FOR_RETRY. dag_id=get_options_data_FB, task_id=create_table, execution_date=20220722T141501, start_date=20220722T141502, end_date=20220722T141502
[2022-07-22 14:15:02,999] {standard_task_runner.py:97} ERROR - Failed to execute job 3 for task create_table (duplicate key value violates unique constraint "pg_type_typname_nsp_index"
DETAIL:  Key (typname, typnamespace)=(fb, 2200) already exists.
; 367)
[2022-07-22 14:15:03,038] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-07-22 14:15:03,102] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
