[2022-07-26 02:32:55,094] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: GOOG_historic_data.load_historic_data_into_postgres manual__2022-07-26T02:32:47.319864+00:00 [queued]>
[2022-07-26 02:32:55,112] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: GOOG_historic_data.load_historic_data_into_postgres manual__2022-07-26T02:32:47.319864+00:00 [queued]>
[2022-07-26 02:32:55,112] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-07-26 02:32:55,113] {taskinstance.py:1377} INFO - Starting attempt 1 of 2
[2022-07-26 02:32:55,113] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-07-26 02:32:55,148] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): load_historic_data_into_postgres> on 2022-07-26 02:32:47.319864+00:00
[2022-07-26 02:32:55,153] {standard_task_runner.py:52} INFO - Started process 16394 to run task
[2022-07-26 02:32:55,158] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'GOOG_historic_data', 'load_historic_data_into_postgres', 'manual__2022-07-26T02:32:47.319864+00:00', '--job-id', '87', '--raw', '--subdir', 'DAGS_FOLDER/open_options.py', '--cfg-path', '/tmp/tmp23voowss', '--error-file', '/tmp/tmp2_2pc4s9']
[2022-07-26 02:32:55,160] {standard_task_runner.py:80} INFO - Job 87: Subtask load_historic_data_into_postgres
[2022-07-26 02:32:55,243] {task_command.py:371} INFO - Running <TaskInstance: GOOG_historic_data.load_historic_data_into_postgres manual__2022-07-26T02:32:47.319864+00:00 [running]> on host 527e7914f635
[2022-07-26 02:32:55,375] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=vardhan
AIRFLOW_CTX_DAG_ID=GOOG_historic_data
AIRFLOW_CTX_TASK_ID=load_historic_data_into_postgres
AIRFLOW_CTX_EXECUTION_DATE=2022-07-26T02:32:47.319864+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-07-26T02:32:47.319864+00:00
[2022-07-26 02:32:55,761] {base.py:68} INFO - Using connection ID 'postgres_optionsdata' for task execution.
[2022-07-26 02:32:55,766] {dbapi.py:231} INFO - Running statement: INSERT INTO GOOG_historic (symbol, date, high_price, low_price, open_price, close_price, total_volume) VALUES ("{'GOOG'}", 1654691040000, 116.95, 116.95, 116.95, 116.95, 4000) ON CONFLICT DO NOTHING, parameters: None
[2022-07-26 02:32:55,771] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/open_options.py", line 337, in load_historic_data_into_postgres
    postgres_hook.run(query_insert % str(row))
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 211, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 235, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UndefinedTable: relation "goog_historic" does not exist
LINE 1: INSERT INTO GOOG_historic (symbol, date, high_price, low_pri...
                    ^

[2022-07-26 02:32:55,787] {taskinstance.py:1420} INFO - Marking task as UP_FOR_RETRY. dag_id=GOOG_historic_data, task_id=load_historic_data_into_postgres, execution_date=20220726T023247, start_date=20220726T023255, end_date=20220726T023255
[2022-07-26 02:32:55,814] {standard_task_runner.py:97} ERROR - Failed to execute job 87 for task load_historic_data_into_postgres (relation "goog_historic" does not exist
LINE 1: INSERT INTO GOOG_historic (symbol, date, high_price, low_pri...
                    ^
; 16394)
[2022-07-26 02:32:55,894] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-07-26 02:32:55,971] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
