[2022-07-26 03:03:35,780] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: GOOG_historic_data.transform_historic_data manual__2022-07-26T03:03:31.126005+00:00 [queued]>
[2022-07-26 03:03:35,795] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: GOOG_historic_data.transform_historic_data manual__2022-07-26T03:03:31.126005+00:00 [queued]>
[2022-07-26 03:03:35,796] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-07-26 03:03:35,796] {taskinstance.py:1377} INFO - Starting attempt 1 of 2
[2022-07-26 03:03:35,796] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-07-26 03:03:35,811] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): transform_historic_data> on 2022-07-26 03:03:31.126005+00:00
[2022-07-26 03:03:35,817] {standard_task_runner.py:52} INFO - Started process 28515 to run task
[2022-07-26 03:03:35,821] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'GOOG_historic_data', 'transform_historic_data', 'manual__2022-07-26T03:03:31.126005+00:00', '--job-id', '129', '--raw', '--subdir', 'DAGS_FOLDER/open_options.py', '--cfg-path', '/tmp/tmpqsq5sbpd', '--error-file', '/tmp/tmpoq4w3ilj']
[2022-07-26 03:03:35,823] {standard_task_runner.py:80} INFO - Job 129: Subtask transform_historic_data
[2022-07-26 03:03:35,920] {task_command.py:371} INFO - Running <TaskInstance: GOOG_historic_data.transform_historic_data manual__2022-07-26T03:03:31.126005+00:00 [running]> on host 527e7914f635
[2022-07-26 03:03:36,031] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=vardhan
AIRFLOW_CTX_DAG_ID=GOOG_historic_data
AIRFLOW_CTX_TASK_ID=transform_historic_data
AIRFLOW_CTX_EXECUTION_DATE=2022-07-26T03:03:31.126005+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-07-26T03:03:31.126005+00:00
[2022-07-26 03:03:36,446] {logging_mixin.py:115} INFO -        date  high_price  low_price  open_price  close_price  total_volume
0       NaN         NaN        NaN         NaN          NaN           NaN
1       NaN         NaN        NaN         NaN          NaN           NaN
2       NaN         NaN        NaN         NaN          NaN           NaN
3       NaN         NaN        NaN         NaN          NaN           NaN
4       NaN         NaN        NaN         NaN          NaN           NaN
...     ...         ...        ...         ...          ...           ...
14015   NaN         NaN        NaN         NaN          NaN           NaN
14016   NaN         NaN        NaN         NaN          NaN           NaN
14017   NaN         NaN        NaN         NaN          NaN           NaN
14018   NaN         NaN        NaN         NaN          NaN           NaN
14019   NaN         NaN        NaN         NaN          NaN           NaN

[14020 rows x 6 columns]
[2022-07-26 03:03:36,518] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/open_options.py", line 206, in transform_historic_data
    df[col] = conv_int(df[col])
  File "/opt/airflow/dags/open_options.py", line 203, in conv_int
    return x.astype(int)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/generic.py", line 5815, in astype
    new_data = self._mgr.astype(dtype=dtype, copy=copy, errors=errors)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/internals/managers.py", line 418, in astype
    return self.apply("astype", dtype=dtype, copy=copy, errors=errors)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/internals/managers.py", line 327, in apply
    applied = getattr(b, f)(**kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/internals/blocks.py", line 591, in astype
    new_values = astype_array_safe(values, dtype, copy=copy, errors=errors)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/dtypes/cast.py", line 1309, in astype_array_safe
    new_values = astype_array(values, dtype, copy=copy)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/dtypes/cast.py", line 1257, in astype_array
    values = astype_nansafe(values, dtype, copy=copy)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/dtypes/cast.py", line 1168, in astype_nansafe
    return astype_float_to_int_nansafe(arr, dtype, copy)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/dtypes/cast.py", line 1214, in astype_float_to_int_nansafe
    "Cannot convert non-finite values (NA or inf) to integer"
pandas.errors.IntCastingNaNError: Cannot convert non-finite values (NA or inf) to integer
[2022-07-26 03:03:36,530] {taskinstance.py:1420} INFO - Marking task as UP_FOR_RETRY. dag_id=GOOG_historic_data, task_id=transform_historic_data, execution_date=20220726T030331, start_date=20220726T030335, end_date=20220726T030336
[2022-07-26 03:03:36,549] {standard_task_runner.py:97} ERROR - Failed to execute job 129 for task transform_historic_data (Cannot convert non-finite values (NA or inf) to integer; 28515)
[2022-07-26 03:03:36,597] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-07-26 03:03:36,988] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
