[2022-07-26 02:40:47,682] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: GOOG_historic_data.load_historic_data_into_postgres manual__2022-07-26T02:39:39.252077+00:00 [queued]>
[2022-07-26 02:40:47,694] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: GOOG_historic_data.load_historic_data_into_postgres manual__2022-07-26T02:39:39.252077+00:00 [queued]>
[2022-07-26 02:40:47,694] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-07-26 02:40:47,694] {taskinstance.py:1377} INFO - Starting attempt 2 of 2
[2022-07-26 02:40:47,694] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-07-26 02:40:47,710] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): load_historic_data_into_postgres> on 2022-07-26 02:39:39.252077+00:00
[2022-07-26 02:40:47,717] {standard_task_runner.py:52} INFO - Started process 19469 to run task
[2022-07-26 02:40:47,720] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'GOOG_historic_data', 'load_historic_data_into_postgres', 'manual__2022-07-26T02:39:39.252077+00:00', '--job-id', '101', '--raw', '--subdir', 'DAGS_FOLDER/open_options.py', '--cfg-path', '/tmp/tmpjkyc4gct', '--error-file', '/tmp/tmp75oepvzv']
[2022-07-26 02:40:47,722] {standard_task_runner.py:80} INFO - Job 101: Subtask load_historic_data_into_postgres
[2022-07-26 02:40:47,806] {task_command.py:371} INFO - Running <TaskInstance: GOOG_historic_data.load_historic_data_into_postgres manual__2022-07-26T02:39:39.252077+00:00 [running]> on host 527e7914f635
[2022-07-26 02:40:47,889] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=vardhan
AIRFLOW_CTX_DAG_ID=GOOG_historic_data
AIRFLOW_CTX_TASK_ID=load_historic_data_into_postgres
AIRFLOW_CTX_EXECUTION_DATE=2022-07-26T02:39:39.252077+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-07-26T02:39:39.252077+00:00
[2022-07-26 02:40:48,263] {base.py:68} INFO - Using connection ID 'postgres_optionsdata' for task execution.
[2022-07-26 02:40:48,267] {dbapi.py:231} INFO - Running statement: INSERT INTO historic_GOOG (symbol, date, high_price, low_price, open_price, close_price, total_volume) VALUES ("{'GOOG'}", 1654691040000, 116.95, 116.95, 116.95, 116.95, 4000) ON CONFLICT DO NOTHING, parameters: None
[2022-07-26 02:40:48,269] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/open_options.py", line 337, in load_historic_data_into_postgres
    postgres_hook.run(query_insert % str(row))
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 211, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 235, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UndefinedColumn: column "{'GOOG'}" does not exist
LINE 1: ...e, open_price, close_price, total_volume) VALUES ("{'GOOG'}"...
                                                             ^

[2022-07-26 02:40:48,282] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=GOOG_historic_data, task_id=load_historic_data_into_postgres, execution_date=20220726T023939, start_date=20220726T024047, end_date=20220726T024048
[2022-07-26 02:40:48,306] {standard_task_runner.py:97} ERROR - Failed to execute job 101 for task load_historic_data_into_postgres (column "{'GOOG'}" does not exist
LINE 1: ...e, open_price, close_price, total_volume) VALUES ("{'GOOG'}"...
                                                             ^
; 19469)
[2022-07-26 02:40:48,336] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-07-26 02:40:48,428] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
