[2022-07-26 02:59:06,981] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: GOOG_historic_data.transform_historic_data manual__2022-07-26T02:58:01.182534+00:00 [queued]>
[2022-07-26 02:59:06,990] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: GOOG_historic_data.transform_historic_data manual__2022-07-26T02:58:01.182534+00:00 [queued]>
[2022-07-26 02:59:06,990] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-07-26 02:59:06,990] {taskinstance.py:1377} INFO - Starting attempt 2 of 2
[2022-07-26 02:59:06,991] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-07-26 02:59:07,003] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): transform_historic_data> on 2022-07-26 02:58:01.182534+00:00
[2022-07-26 02:59:07,007] {standard_task_runner.py:52} INFO - Started process 26661 to run task
[2022-07-26 02:59:07,012] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'GOOG_historic_data', 'transform_historic_data', 'manual__2022-07-26T02:58:01.182534+00:00', '--job-id', '110', '--raw', '--subdir', 'DAGS_FOLDER/open_options.py', '--cfg-path', '/tmp/tmpsjgheptx', '--error-file', '/tmp/tmpwcnu69w2']
[2022-07-26 02:59:07,014] {standard_task_runner.py:80} INFO - Job 110: Subtask transform_historic_data
[2022-07-26 02:59:07,093] {task_command.py:371} INFO - Running <TaskInstance: GOOG_historic_data.transform_historic_data manual__2022-07-26T02:58:01.182534+00:00 [running]> on host 527e7914f635
[2022-07-26 02:59:07,203] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=vardhan
AIRFLOW_CTX_DAG_ID=GOOG_historic_data
AIRFLOW_CTX_TASK_ID=transform_historic_data
AIRFLOW_CTX_EXECUTION_DATE=2022-07-26T02:58:01.182534+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-07-26T02:58:01.182534+00:00
[2022-07-26 02:59:07,683] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/open_options.py", line 186, in transform_historic_data
    df = pd.DataFrame(extract_data, columns=columns)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/frame.py", line 717, in __init__
    typ=manager,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/internals/construction.py", line 324, in ndarray_to_mgr
    _check_values_indices_shape_match(values, index, columns)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/internals/construction.py", line 393, in _check_values_indices_shape_match
    raise ValueError(f"Shape of passed values is {passed}, indices imply {implied}")
ValueError: Shape of passed values is (14021, 1), indices imply (14021, 7)
[2022-07-26 02:59:07,698] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=GOOG_historic_data, task_id=transform_historic_data, execution_date=20220726T025801, start_date=20220726T025906, end_date=20220726T025907
[2022-07-26 02:59:07,723] {standard_task_runner.py:97} ERROR - Failed to execute job 110 for task transform_historic_data (Shape of passed values is (14021, 1), indices imply (14021, 7); 26661)
[2022-07-26 02:59:07,784] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-07-26 02:59:07,890] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
