[2022-07-26 04:25:51,848] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: GOOG_historic_data.load_historic_data_into_postgres manual__2022-07-26T04:24:40.871295+00:00 [queued]>
[2022-07-26 04:25:51,857] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: GOOG_historic_data.load_historic_data_into_postgres manual__2022-07-26T04:24:40.871295+00:00 [queued]>
[2022-07-26 04:25:51,858] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-07-26 04:25:51,858] {taskinstance.py:1377} INFO - Starting attempt 2 of 2
[2022-07-26 04:25:51,858] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-07-26 04:25:51,873] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): load_historic_data_into_postgres> on 2022-07-26 04:24:40.871295+00:00
[2022-07-26 04:25:51,877] {standard_task_runner.py:52} INFO - Started process 60866 to run task
[2022-07-26 04:25:51,880] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'GOOG_historic_data', 'load_historic_data_into_postgres', 'manual__2022-07-26T04:24:40.871295+00:00', '--job-id', '174', '--raw', '--subdir', 'DAGS_FOLDER/open_options.py', '--cfg-path', '/tmp/tmpu9rqyhj6', '--error-file', '/tmp/tmp8nb6l0nd']
[2022-07-26 04:25:51,881] {standard_task_runner.py:80} INFO - Job 174: Subtask load_historic_data_into_postgres
[2022-07-26 04:25:51,944] {task_command.py:371} INFO - Running <TaskInstance: GOOG_historic_data.load_historic_data_into_postgres manual__2022-07-26T04:24:40.871295+00:00 [running]> on host 527e7914f635
[2022-07-26 04:25:52,050] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=vardhan
AIRFLOW_CTX_DAG_ID=GOOG_historic_data
AIRFLOW_CTX_TASK_ID=load_historic_data_into_postgres
AIRFLOW_CTX_EXECUTION_DATE=2022-07-26T04:24:40.871295+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-07-26T04:24:40.871295+00:00
[2022-07-26 04:25:52,455] {base.py:68} INFO - Using connection ID 'postgres_optionsdata' for task execution.
[2022-07-26 04:25:52,462] {dbapi.py:231} INFO - Running statement: INSERT INTO historic__GOOG (datetime, high, low, open, close, volume, symbol) VALUES (1654691040000, 116.95, 116.95, 116.95, 116.95, 4000, 'GOOG') ON CONFLICT DO NOTHING, parameters: None
[2022-07-26 04:25:52,465] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/open_options.py", line 332, in load_historic_data_into_postgres
    postgres_hook.run(query_insert % str(row))
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 211, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 235, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UndefinedColumn: column "symbol" of relation "historic__goog" does not exist
LINE 1: ...__GOOG (datetime, high, low, open, close, volume, symbol) VA...
                                                             ^

[2022-07-26 04:25:52,483] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=GOOG_historic_data, task_id=load_historic_data_into_postgres, execution_date=20220726T042440, start_date=20220726T042551, end_date=20220726T042552
[2022-07-26 04:25:52,515] {standard_task_runner.py:97} ERROR - Failed to execute job 174 for task load_historic_data_into_postgres (column "symbol" of relation "historic__goog" does not exist
LINE 1: ...__GOOG (datetime, high, low, open, close, volume, symbol) VA...
                                                             ^
; 60866)
[2022-07-26 04:25:52,576] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-07-26 04:25:52,704] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
