[2022-07-26 03:15:05,704] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: GOOG_historic_data.create_historic_table manual__2022-07-26T03:15:04.550266+00:00 [queued]>
[2022-07-26 03:15:05,719] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: GOOG_historic_data.create_historic_table manual__2022-07-26T03:15:04.550266+00:00 [queued]>
[2022-07-26 03:15:05,719] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-07-26 03:15:05,720] {taskinstance.py:1377} INFO - Starting attempt 1 of 2
[2022-07-26 03:15:05,720] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-07-26 03:15:05,760] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): create_historic_table> on 2022-07-26 03:15:04.550266+00:00
[2022-07-26 03:15:05,766] {standard_task_runner.py:52} INFO - Started process 33178 to run task
[2022-07-26 03:15:05,769] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'GOOG_historic_data', 'create_historic_table', 'manual__2022-07-26T03:15:04.550266+00:00', '--job-id', '161', '--raw', '--subdir', 'DAGS_FOLDER/open_options.py', '--cfg-path', '/tmp/tmpgejobx2u', '--error-file', '/tmp/tmpm7zi2nm_']
[2022-07-26 03:15:05,770] {standard_task_runner.py:80} INFO - Job 161: Subtask create_historic_table
[2022-07-26 03:15:05,841] {task_command.py:371} INFO - Running <TaskInstance: GOOG_historic_data.create_historic_table manual__2022-07-26T03:15:04.550266+00:00 [running]> on host 527e7914f635
[2022-07-26 03:15:05,949] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=vardhan
AIRFLOW_CTX_DAG_ID=GOOG_historic_data
AIRFLOW_CTX_TASK_ID=create_historic_table
AIRFLOW_CTX_EXECUTION_DATE=2022-07-26T03:15:04.550266+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-07-26T03:15:04.550266+00:00
[2022-07-26 03:15:05,960] {base.py:68} INFO - Using connection ID 'postgres_optionsdata' for task execution.
[2022-07-26 03:15:05,966] {dbapi.py:231} INFO - Running statement: 
        CREATE TABLE IF NOT EXISTS historic__GOOG (
            datetime BIGINT,
            high DOUBLE PRECISION,
            low DOUBLE PRECISION,
            open DOUBLE PRECISION,
            close DOUBLE PRECISION,
            volume INTEGER,
            PRIMARY KEY (date)
        )
    , parameters: None
[2022-07-26 03:15:05,968] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/open_options.py", line 43, in create_table_historic_data
    """)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 211, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 235, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UndefinedColumn: column "date" named in key does not exist
LINE 9:             PRIMARY KEY (date)
                    ^

[2022-07-26 03:15:05,986] {taskinstance.py:1420} INFO - Marking task as UP_FOR_RETRY. dag_id=GOOG_historic_data, task_id=create_historic_table, execution_date=20220726T031504, start_date=20220726T031505, end_date=20220726T031505
[2022-07-26 03:15:06,004] {standard_task_runner.py:97} ERROR - Failed to execute job 161 for task create_historic_table (column "date" named in key does not exist
LINE 9:             PRIMARY KEY (date)
                    ^
; 33178)
[2022-07-26 03:15:06,023] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-07-26 03:15:06,129] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
